export const LIST_COUNTRY = [
    {
        "id":53,
        "country_name":"Afghanistan"
    },
    {
        "id":54,
        "country_name":"Åland Islands"
    },
    {
        "id":55,
        "country_name":"Albania"
    },
    {
        "id":56,
        "country_name":"Algeria"
    },
    {
        "id":57,
        "country_name":"American Samoa"
    },
    {
        "id":58,
        "country_name":"AndorrA"
    },
    {
        "id":59,
        "country_name":"Angola"
    },
    {
        "id":60,
        "country_name":"Anguilla"
    },
    {
        "id":61,
        "country_name":"Antarctica"
    },
    {
        "id":62,
        "country_name":"Antigua and Barbuda"
    },
    {
        "id":63,
        "country_name":"Argentina"
    },
    {
        "id":64,
        "country_name":"Armenia"
    },
    {
        "id":65,
        "country_name":"Aruba"
    },
    {
        "id":66,
        "country_name":"Australia"
    },
    {
        "id":67,
        "country_name":"Austria"
    },
    {
        "id":68,
        "country_name":"Azerbaijan"
    },
    {
        "id":69,
        "country_name":"Bahamas"
    },
    {
        "id":70,
        "country_name":"Bahrain"
    },
    {
        "id":71,
        "country_name":"Bangladesh"
    },
    {
        "id":72,
        "country_name":"Barbados"
    },
    {
        "id":73,
        "country_name":"Belarus"
    },
    {
        "id":74,
        "country_name":"Belgium"
    },
    {
        "id":75,
        "country_name":"Belize"
    },
    {
        "id":76,
        "country_name":"Benin"
    },
    {
        "id":77,
        "country_name":"Bermuda"
    },
    {
        "id":78,
        "country_name":"Bhutan"
    },
    {
        "id":79,
        "country_name":"Bolivia"
    },
    {
        "id":80,
        "country_name":"Bosnia and Herzegovina"
    },
    {
        "id":81,
        "country_name":"Botswana"
    },
    {
        "id":82,
        "country_name":"Bouvet Island"
    },
    {
        "id":83,
        "country_name":"Brazil"
    },
    {
        "id":84,
        "country_name":"British Indian Ocean Territory"
    },
    {
        "id":85,
        "country_name":"Brunei Darussalam"
    },
    {
        "id":86,
        "country_name":"Bulgaria"
    },
    {
        "id":87,
        "country_name":"Burkina Faso"
    },
    {
        "id":88,
        "country_name":"Burundi"
    },
    {
        "id":89,
        "country_name":"Cambodia"
    },
    {
        "id":90,
        "country_name":"Cameroon"
    },
    {
        "id":91,
        "country_name":"Canada"
    },
    {
        "id":92,
        "country_name":"Cape Verde"
    },
    {
        "id":93,
        "country_name":"Cayman Islands"
    },
    {
        "id":94,
        "country_name":"Central African Republic"
    },
    {
        "id":95,
        "country_name":"Chad"
    },
    {
        "id":96,
        "country_name":"Chile"
    },
    {
        "id":97,
        "country_name":"China"
    },
    {
        "id":98,
        "country_name":"Christmas Island"
    },
    {
        "id":99,
        "country_name":"Cocos (Keeling) Islands"
    },
    {
        "id":100,
        "country_name":"Colombia"
    },
    {
        "id":101,
        "country_name":"Comoros"
    },
    {
        "id":102,
        "country_name":"Congo"
    },
    {
        "id":103,
        "country_name":"Congo, The Democratic Republic of the"
    },
    {
        "id":104,
        "country_name":"Cook Islands"
    },
    {
        "id":105,
        "country_name":"Costa Rica"
    },
    {
        "id":106,
        "country_name":"Cote D'Ivoire"
    },
    {
        "id":107,
        "country_name":"Croatia"
    },
    {
        "id":108,
        "country_name":"Cuba"
    },
    {
        "id":109,
        "country_name":"Cyprus"
    },
    {
        "id":110,
        "country_name":"Czech Republic"
    },
    {
        "id":111,
        "country_name":"Denmark"
    },
    {
        "id":112,
        "country_name":"Djibouti"
    },
    {
        "id":113,
        "country_name":"Dominica"
    },
    {
        "id":114,
        "country_name":"Dominican Republic"
    },
    {
        "id":115,
        "country_name":"Ecuador"
    },
    {
        "id":116,
        "country_name":"Egypt"
    },
    {
        "id":117,
        "country_name":"El Salvador"
    },
    {
        "id":118,
        "country_name":"Equatorial Guinea"
    },
    {
        "id":119,
        "country_name":"Eritrea"
    },
    {
        "id":120,
        "country_name":"Estonia"
    },
    {
        "id":121,
        "country_name":"Ethiopia"
    },
    {
        "id":122,
        "country_name":"Falkland Islands (Malvinas)"
    },
    {
        "id":123,
        "country_name":"Faroe Islands"
    },
    {
        "id":124,
        "country_name":"Fiji"
    },
    {
        "id":125,
        "country_name":"Finland"
    },
    {
        "id":126,
        "country_name":"France"
    },
    {
        "id":127,
        "country_name":"French Guiana"
    },
    {
        "id":128,
        "country_name":"French Polynesia"
    },
    {
        "id":129,
        "country_name":"French Southern Territories"
    },
    {
        "id":130,
        "country_name":"Gabon"
    },
    {
        "id":131,
        "country_name":"Gambia"
    },
    {
        "id":132,
        "country_name":"Georgia"
    },
    {
        "id":133,
        "country_name":"Germany"
    },
    {
        "id":134,
        "country_name":"Ghana"
    },
    {
        "id":135,
        "country_name":"Gibraltar"
    },
    {
        "id":136,
        "country_name":"Greece"
    },
    {
        "id":137,
        "country_name":"Greenland"
    },
    {
        "id":138,
        "country_name":"Grenada"
    },
    {
        "id":139,
        "country_name":"Guadeloupe"
    },
    {
        "id":140,
        "country_name":"Guam"
    },
    {
        "id":141,
        "country_name":"Guatemala"
    },
    {
        "id":142,
        "country_name":"Guernsey"
    },
    {
        "id":143,
        "country_name":"Guinea"
    },
    {
        "id":144,
        "country_name":"Guinea-Bissau"
    },
    {
        "id":145,
        "country_name":"Guyana"
    },
    {
        "id":146,
        "country_name":"Haiti"
    },
    {
        "id":147,
        "country_name":"Heard Island and Mcdonald Islands"
    },
    {
        "id":148,
        "country_name":"Holy See (Vatican City State)"
    },
    {
        "id":149,
        "country_name":"Honduras"
    },
    {
        "id":150,
        "country_name":"Hong Kong"
    },
    {
        "id":151,
        "country_name":"Hungary"
    },
    {
        "id":152,
        "country_name":"Iceland"
    },
    {
        "id":153,
        "country_name":"India"
    },
    {
        "id":154,
        "country_name":"Indonesia"
    },
    {
        "id":155,
        "country_name":"Iran, Islamic Republic Of"
    },
    {
        "id":156,
        "country_name":"Iraq"
    },
    {
        "id":157,
        "country_name":"Ireland"
    },
    {
        "id":158,
        "country_name":"Isle of Man"
    },
    {
        "id":159,
        "country_name":"Israel"
    },
    {
        "id":160,
        "country_name":"Italy"
    },
    {
        "id":161,
        "country_name":"Jamaica"
    },
    {
        "id":162,
        "country_name":"Japan"
    },
    {
        "id":163,
        "country_name":"Jersey"
    },
    {
        "id":164,
        "country_name":"Jordan"
    },
    {
        "id":165,
        "country_name":"Kazakhstan"
    },
    {
        "id":166,
        "country_name":"Kenya"
    },
    {
        "id":167,
        "country_name":"Kiribati"
    },
    {
        "id":168,
        "country_name":"Korea, Democratic People'S Republic of"
    },
    {
        "id":169,
        "country_name":"Korea, Republic of"
    },
    {
        "id":170,
        "country_name":"Kuwait"
    },
    {
        "id":171,
        "country_name":"Kyrgyzstan"
    },
    {
        "id":172,
        "country_name":"Lao People'S Democratic Republic"
    },
    {
        "id":173,
        "country_name":"Latvia"
    },
    {
        "id":174,
        "country_name":"Lebanon"
    },
    {
        "id":175,
        "country_name":"Lesotho"
    },
    {
        "id":176,
        "country_name":"Liberia"
    },
    {
        "id":177,
        "country_name":"Libyan Arab Jamahiriya"
    },
    {
        "id":178,
        "country_name":"Liechtenstein"
    },
    {
        "id":179,
        "country_name":"Lithuania"
    },
    {
        "id":180,
        "country_name":"Luxembourg"
    },
    {
        "id":181,
        "country_name":"Macao"
    },
    {
        "id":182,
        "country_name":"Macedonia, The Former Yugoslav Republic of"
    },
    {
        "id":183,
        "country_name":"Madagascar"
    },
    {
        "id":184,
        "country_name":"Malawi"
    },
    {
        "id":185,
        "country_name":"Malaysia"
    },
    {
        "id":186,
        "country_name":"Maldives"
    },
    {
        "id":187,
        "country_name":"Mali"
    },
    {
        "id":188,
        "country_name":"Malta"
    },
    {
        "id":189,
        "country_name":"Marshall Islands"
    },
    {
        "id":190,
        "country_name":"Martinique"
    },
    {
        "id":191,
        "country_name":"Mauritania"
    },
    {
        "id":192,
        "country_name":"Mauritius"
    },
    {
        "id":193,
        "country_name":"Mayotte"
    },
    {
        "id":194,
        "country_name":"Mexico"
    },
    {
        "id":195,
        "country_name":"Micronesia, Federated States of"
    },
    {
        "id":196,
        "country_name":"Moldova, Republic of"
    },
    {
        "id":197,
        "country_name":"Monaco"
    },
    {
        "id":198,
        "country_name":"Mongolia"
    },
    {
        "id":199,
        "country_name":"Montserrat"
    },
    {
        "id":200,
        "country_name":"Morocco"
    },
    {
        "id":201,
        "country_name":"Mozambique"
    },
    {
        "id":202,
        "country_name":"Myanmar"
    },
    {
        "id":203,
        "country_name":"Namibia"
    },
    {
        "id":204,
        "country_name":"Nauru"
    },
    {
        "id":205,
        "country_name":"Nepal"
    },
    {
        "id":206,
        "country_name":"Netherlands"
    },
    {
        "id":207,
        "country_name":"Netherlands Antilles"
    },
    {
        "id":208,
        "country_name":"New Caledonia"
    },
    {
        "id":209,
        "country_name":"New Zealand"
    },
    {
        "id":210,
        "country_name":"Nicaragua"
    },
    {
        "id":211,
        "country_name":"Niger"
    },
    {
        "id":212,
        "country_name":"Nigeria"
    },
    {
        "id":213,
        "country_name":"Niue"
    },
    {
        "id":214,
        "country_name":"Norfolk Island"
    },
    {
        "id":215,
        "country_name":"Northern Mariana Islands"
    },
    {
        "id":216,
        "country_name":"Norway"
    },
    {
        "id":217,
        "country_name":"Oman"
    },
    {
        "id":218,
        "country_name":"Pakistan"
    },
    {
        "id":219,
        "country_name":"Palau"
    },
    {
        "id":220,
        "country_name":"Palestinian Territory, Occupied"
    },
    {
        "id":221,
        "country_name":"Panama"
    },
    {
        "id":222,
        "country_name":"Papua New Guinea"
    },
    {
        "id":223,
        "country_name":"Paraguay"
    },
    {
        "id":224,
        "country_name":"Peru"
    },
    {
        "id":225,
        "country_name":"Philippines"
    },
    {
        "id":226,
        "country_name":"Pitcairn"
    },
    {
        "id":227,
        "country_name":"Poland"
    },
    {
        "id":228,
        "country_name":"Portugal"
    },
    {
        "id":229,
        "country_name":"Puerto Rico"
    },
    {
        "id":230,
        "country_name":"Qatar"
    },
    {
        "id":231,
        "country_name":"Reunion"
    },
    {
        "id":232,
        "country_name":"Romania"
    },
    {
        "id":233,
        "country_name":"Russian Federation"
    },
    {
        "id":234,
        "country_name":"RWANDA"
    },
    {
        "id":235,
        "country_name":"Saint Helena"
    },
    {
        "id":236,
        "country_name":"Saint Kitts and Nevis"
    },
    {
        "id":237,
        "country_name":"Saint Lucia"
    },
    {
        "id":238,
        "country_name":"Saint Pierre and Miquelon"
    },
    {
        "id":239,
        "country_name":"Saint Vincent and the Grenadines"
    },
    {
        "id":240,
        "country_name":"Samoa"
    },
    {
        "id":241,
        "country_name":"San Marino"
    },
    {
        "id":242,
        "country_name":"Sao Tome and Principe"
    },
    {
        "id":243,
        "country_name":"Saudi Arabia"
    },
    {
        "id":244,
        "country_name":"Senegal"
    },
    {
        "id":245,
        "country_name":"Serbia and Montenegro"
    },
    {
        "id":246,
        "country_name":"Seychelles"
    },
    {
        "id":247,
        "country_name":"Sierra Leone"
    },
    {
        "id":248,
        "country_name":"Singapore"
    },
    {
        "id":249,
        "country_name":"Slovakia"
    },
    {
        "id":250,
        "country_name":"Slovenia"
    },
    {
        "id":251,
        "country_name":"Solomon Islands"
    },
    {
        "id":252,
        "country_name":"Somalia"
    },
    {
        "id":253,
        "country_name":"South Africa"
    },
    {
        "id":254,
        "country_name":"South Georgia and the South Sandwich Islands"
    },
    {
        "id":255,
        "country_name":"Spain"
    },
    {
        "id":256,
        "country_name":"Sri Lanka"
    },
    {
        "id":257,
        "country_name":"Sudan"
    },
    {
        "id":258,
        "country_name":"Suriname"
    },
    {
        "id":259,
        "country_name":"Svalbard and Jan Mayen"
    },
    {
        "id":260,
        "country_name":"Swaziland"
    },
    {
        "id":261,
        "country_name":"Sweden"
    },
    {
        "id":262,
        "country_name":"Switzerland"
    },
    {
        "id":263,
        "country_name":"Syrian Arab Republic"
    },
    {
        "id":264,
        "country_name":"Taiwan, Province of China"
    },
    {
        "id":265,
        "country_name":"Tajikistan"
    },
    {
        "id":266,
        "country_name":"Tanzania, United Republic of"
    },
    {
        "id":267,
        "country_name":"Thailand"
    },
    {
        "id":268,
        "country_name":"Timor-Leste"
    },
    {
        "id":269,
        "country_name":"Togo"
    },
    {
        "id":270,
        "country_name":"Tokelau"
    },
    {
        "id":271,
        "country_name":"Tonga"
    },
    {
        "id":272,
        "country_name":"Trinidad and Tobago"
    },
    {
        "id":273,
        "country_name":"Tunisia"
    },
    {
        "id":274,
        "country_name":"Turkey"
    },
    {
        "id":275,
        "country_name":"Turkmenistan"
    },
    {
        "id":276,
        "country_name":"Turks and Caicos Islands"
    },
    {
        "id":277,
        "country_name":"Tuvalu"
    },
    {
        "id":278,
        "country_name":"Uganda"
    },
    {
        "id":279,
        "country_name":"Ukraine"
    },
    {
        "id":280,
        "country_name":"United Arab Emirates"
    },
    {
        "id":281,
        "country_name":"United Kingdom"
    },
    {
        "id":282,
        "country_name":"United States"
    },
    {
        "id":283,
        "country_name":"United States Minor Outlying Islands"
    },
    {
        "id":284,
        "country_name":"Uruguay"
    },
    {
        "id":285,
        "country_name":"Uzbekistan"
    },
    {
        "id":286,
        "country_name":"Vanuatu"
    },
    {
        "id":287,
        "country_name":"Venezuela"
    },
    {
        "id":288,
        "country_name":"Viet Nam"
    },
    {
        "id":289,
        "country_name":"Virgin Islands, British"
    },
    {
        "id":290,
        "country_name":"Virgin Islands, U.S."
    },
    {
        "id":291,
        "country_name":"Wallis and Futuna"
    },
    {
        "id":292,
        "country_name":"Western Sahara"
    },
    {
        "id":293,
        "country_name":"Yemen"
    },
    {
        "id":294,
        "country_name":"Zambia"
    },
    {
        "id":295,
        "country_name":"Zimbabwe"
    }
];