export default {
    "VALIDATION": "1",
    "GLOBAL": "2",

    "AUTHENTICATION": "10",
    "JWT_TOKEN_EXPIRED": "11",
    "DUPPLICATE_EMAIL": "12",
    "DUPPLICATE_USERNAME": "13",
    "DUPPLICATE_ADDRESS": "14",
    "USER_NOT_FOUND": "15",
    "OLD_PASSWORD_OR_NEW_PASSWORD_INVALID": "16",
    "DIMENSION_IS_EMPTY": "17",
    "CARRIER_NOT_FOUND": "18",
    "JWT_TOKEN_INVALID": "19"
};
